/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	secretsv1alpha1 "github.com/captncraig/secretOperator/pkg/apis/secrets/v1alpha1"
	versioned "github.com/captncraig/secretOperator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/captncraig/secretOperator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/captncraig/secretOperator/pkg/client/listers/secrets/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VaultSecretInformer provides access to a shared informer and lister for
// VaultSecrets.
type VaultSecretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VaultSecretLister
}

type vaultSecretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVaultSecretInformer constructs a new informer for VaultSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVaultSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVaultSecretInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVaultSecretInformer constructs a new informer for VaultSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVaultSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretsV1alpha1().VaultSecrets(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretsV1alpha1().VaultSecrets(namespace).Watch(options)
			},
		},
		&secretsv1alpha1.VaultSecret{},
		resyncPeriod,
		indexers,
	)
}

func (f *vaultSecretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVaultSecretInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vaultSecretInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&secretsv1alpha1.VaultSecret{}, f.defaultInformer)
}

func (f *vaultSecretInformer) Lister() v1alpha1.VaultSecretLister {
	return v1alpha1.NewVaultSecretLister(f.Informer().GetIndexer())
}
