apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: randomsecrets.secrets.k8s.captncraig.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: secrets.k8s.captncraig.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: randomsecrets
    # singular name to be used as an alias on the CLI and for display
    singular: randomsecret
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: RandomSecret
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - randsec